# Generated by Django 3.0.4 on 2020-03-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20200311_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_with_type', to='recruiters.CompanyType'),
        ),
    ]
