# Generated by Django 3.0.4 on 2020-03-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0002_auto_20200311_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('Job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.JobDescription')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.Batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.Branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.Recruiter')),
            ],
        ),
    ]
