# Generated by Django 3.0.4 on 2020-03-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_auto_20200311_1357'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_job_roles', to='placements.JobDescription'),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_of_batch', to='placements.Batch'),
        ),
        migrations.AlterField(
            model_name='students',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_chosen_branch', to='placements.Branch'),
        ),
        migrations.AlterField(
            model_name='students',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_company_name', to='recruiters.Recruiter'),
        ),
    ]
