# Generated by Django 3.0.4 on 2020-03-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('winner_declared', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('iam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.IAM')),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('iam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.IAM')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=255)),
                ('iam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.IAM')),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='iam/speakers')),
                ('designation', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('iam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.IAM')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.Tracks'),
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.IAM')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IAM.Projects')),
            ],
        ),
    ]
