# Generated by Django 3.0.4 on 2020-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IAM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iam',
            name='logo',
            field=models.FileField(blank=True, upload_to='iam/logo'),
        ),
    ]
