# Generated by Django 3.0.4 on 2020-03-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IAM', '0002_iam_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='IAM.Projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_track', to='IAM.Tracks'),
        ),
        migrations.AlterField(
            model_name='winners',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners_project', to='IAM.Projects'),
        ),
    ]
