# Generated by Django 3.0.4 on 2020-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
